name: Auto-Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
      sync:
        runs-on: ubuntu-latest
        steps:
          - name: Sync default branch (dev)
            run: gh repo sync $GITHUB_REPOSITORY
            env:
              GH_TOKEN: ${{ secrets.PAT_TOKEN }}
              
          - name: Sync legacy branch
            run: gh repo sync $GITHUB_REPOSITORY --branch legacy
            env:
              GH_TOKEN: ${{ secrets.PAT_TOKEN }}

          - name: Sync sync-upstream branch
            run: gh repo sync $GITHUB_REPOSITORY --branch sync-upstream
            env:
              GH_TOKEN: ${{ secrets.PAT_TOKEN }}
